
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xarray_inverter.h"

/*
* The configuration table for devices
*/

XArray_inverter_Config XArray_inverter_ConfigTable[XPAR_XARRAY_INVERTER_NUM_INSTANCES] =
{
	{
		XPAR_ARRAY_INVERTER_0_DEVICE_ID,
		XPAR_ARRAY_INVERTER_0_S_AXI_AXI_CPU_BASEADDR
	}
};


